name: Chrome
on:
  workflow_dispatch:
    inputs:
      config-file:
        type: choice
        description: "--env configFile="
        required: true
        options:
          - "duck.demo"
          - "azure.lime"
          - "gcp.lime"
          - "host.env"

jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: greet
        run: |
          echo 'configFile is ${{ github.event.inputs.config-file }}'

      - name: Cypress run with env
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        env:
          CYPRESS_configFile: ${{ github.event.inputs.config-file }}
          DEBUG: "cypress:*"

      - name: Cypress screenshots on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - name: Cypress videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
